import { ViewStyle } from "react-native"

export const spacing = {
  none: 0,
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 24,
  xxl: 32,
  xxxl: 48,
} as const

export const $spacingStyles = {
  // ===== Margin =====
  mXs: { margin: spacing.xs } as ViewStyle,
  mSm: { margin: spacing.sm } as ViewStyle,
  mMd: { margin: spacing.md } as ViewStyle,
  mLg: { margin: spacing.lg } as ViewStyle,
  mXl: { margin: spacing.xl } as ViewStyle,
  mXxl: { margin: spacing.xxl } as ViewStyle,
  mXxxl: { margin: spacing.xxxl } as ViewStyle,

  mtXs: { marginTop: spacing.xs } as ViewStyle,
  mtSm: { marginTop: spacing.sm } as ViewStyle,
  mtMd: { marginTop: spacing.md } as ViewStyle,
  mtLg: { marginTop: spacing.lg } as ViewStyle,
  mtXl: { marginTop: spacing.xl } as ViewStyle,
  mtXxl: { marginTop: spacing.xxl } as ViewStyle,
  mtXxxl: { marginTop: spacing.xxxl } as ViewStyle,

  mbXs: { marginBottom: spacing.xs } as ViewStyle,
  mbSm: { marginBottom: spacing.sm } as ViewStyle,
  mbMd: { marginBottom: spacing.md } as ViewStyle,
  mbLg: { marginBottom: spacing.lg } as ViewStyle,
  mbXl: { marginBottom: spacing.xl } as ViewStyle,
  mbXxl: { marginBottom: spacing.xxl } as ViewStyle,
  mbXxxl: { marginBottom: spacing.xxxl } as ViewStyle,

  mlXs: { marginLeft: spacing.xs } as ViewStyle,
  mlSm: { marginLeft: spacing.sm } as ViewStyle,
  mlMd: { marginLeft: spacing.md } as ViewStyle,
  mlLg: { marginLeft: spacing.lg } as ViewStyle,
  mlXl: { marginLeft: spacing.xl } as ViewStyle,
  mlXxl: { marginLeft: spacing.xxl } as ViewStyle,
  mlXxxl: { marginLeft: spacing.xxxl } as ViewStyle,

  mrXs: { marginRight: spacing.xs } as ViewStyle,
  mrSm: { marginRight: spacing.sm } as ViewStyle,
  mrMd: { marginRight: spacing.md } as ViewStyle,
  mrLg: { marginRight: spacing.lg } as ViewStyle,
  mrXl: { marginRight: spacing.xl } as ViewStyle,
  mrXxl: { marginRight: spacing.xxl } as ViewStyle,
  mrXxxl: { marginRight: spacing.xxxl } as ViewStyle,

  mxXs: { marginHorizontal: spacing.xs } as ViewStyle,
  mxSm: { marginHorizontal: spacing.sm } as ViewStyle,
  mxMd: { marginHorizontal: spacing.md } as ViewStyle,
  mxLg: { marginHorizontal: spacing.lg } as ViewStyle,
  mxXl: { marginHorizontal: spacing.xl } as ViewStyle,
  mxXxl: { marginHorizontal: spacing.xxl } as ViewStyle,
  mxXxxl: { marginHorizontal: spacing.xxxl } as ViewStyle,

  myXs: { marginVertical: spacing.xs } as ViewStyle,
  mySm: { marginVertical: spacing.sm } as ViewStyle,
  myMd: { marginVertical: spacing.md } as ViewStyle,
  myLg: { marginVertical: spacing.lg } as ViewStyle,
  myXl: { marginVertical: spacing.xl } as ViewStyle,
  myXxl: { marginVertical: spacing.xxl } as ViewStyle,
  myXxxl: { marginVertical: spacing.xxxl } as ViewStyle,

  // ===== Padding =====
  pXs: { padding: spacing.xs } as ViewStyle,
  pSm: { padding: spacing.sm } as ViewStyle,
  pMd: { padding: spacing.md } as ViewStyle,
  pLg: { padding: spacing.lg } as ViewStyle,
  pXl: { padding: spacing.xl } as ViewStyle,
  pXxl: { padding: spacing.xxl } as ViewStyle,
  pXxxl: { padding: spacing.xxxl } as ViewStyle,

  ptXs: { paddingTop: spacing.xs } as ViewStyle,
  ptSm: { paddingTop: spacing.sm } as ViewStyle,
  ptMd: { paddingTop: spacing.md } as ViewStyle,
  ptLg: { paddingTop: spacing.lg } as ViewStyle,
  ptXl: { paddingTop: spacing.xl } as ViewStyle,
  ptXxl: { paddingTop: spacing.xxl } as ViewStyle,
  ptXxxl: { paddingTop: spacing.xxxl } as ViewStyle,

  pbXs: { paddingBottom: spacing.xs } as ViewStyle,
  pbSm: { paddingBottom: spacing.sm } as ViewStyle,
  pbMd: { paddingBottom: spacing.md } as ViewStyle,
  pbLg: { paddingBottom: spacing.lg } as ViewStyle,
  pbXl: { paddingBottom: spacing.xl } as ViewStyle,
  pbXxl: { paddingBottom: spacing.xxl } as ViewStyle,
  pbXxxl: { paddingBottom: spacing.xxxl } as ViewStyle,

  plXs: { paddingLeft: spacing.xs } as ViewStyle,
  plSm: { paddingLeft: spacing.sm } as ViewStyle,
  plMd: { paddingLeft: spacing.md } as ViewStyle,
  plLg: { paddingLeft: spacing.lg } as ViewStyle,
  plXl: { paddingLeft: spacing.xl } as ViewStyle,
  plXxl: { paddingLeft: spacing.xxl } as ViewStyle,
  plXxxl: { paddingLeft: spacing.xxxl } as ViewStyle,

  prXs: { paddingRight: spacing.xs } as ViewStyle,
  prSm: { paddingRight: spacing.sm } as ViewStyle,
  prMd: { paddingRight: spacing.md } as ViewStyle,
  prLg: { paddingRight: spacing.lg } as ViewStyle,
  prXl: { paddingRight: spacing.xl } as ViewStyle,
  prXxl: { paddingRight: spacing.xxl } as ViewStyle,
  prXxxl: { paddingRight: spacing.xxxl } as ViewStyle,

  pxXs: { paddingHorizontal: spacing.xs } as ViewStyle,
  pxSm: { paddingHorizontal: spacing.sm } as ViewStyle,
  pxMd: { paddingHorizontal: spacing.md } as ViewStyle,
  pxLg: { paddingHorizontal: spacing.lg } as ViewStyle,
  pxXl: { paddingHorizontal: spacing.xl } as ViewStyle,
  pxXxl: { paddingHorizontal: spacing.xxl } as ViewStyle,
  pxXxxl: { paddingHorizontal: spacing.xxxl } as ViewStyle,

  pyXs: { paddingVertical: spacing.xs } as ViewStyle,
  pySm: { paddingVertical: spacing.sm } as ViewStyle,
  pyMd: { paddingVertical: spacing.md } as ViewStyle,
  pyLg: { paddingVertical: spacing.lg } as ViewStyle,
  pyXl: { paddingVertical: spacing.xl } as ViewStyle,
  pyXxl: { paddingVertical: spacing.xxl } as ViewStyle,
  pyXxxl: { paddingVertical: spacing.xxxl } as ViewStyle,
}
